sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t cwilko/smart-home-actions:arm32v7 .

script:
  - docker run -d --rm cwilko/smart-home-actions:arm32v7
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cwilko/smart-home-actions:arm32v7